language: node_js
node_js: node
cache:
  directories:
    - node_modules
#script:
#  - npm run lint
env:
  - CI=true

before_deploy:
  - npm install -g @vue/cli
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t NETLIFY_PUBLISH_KEY   -p ./dist
  skip_cleanup: true
  on:
    branch: master

